steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCS init"]
  - id: 'terraform validate'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCS validate"]   
  - id: 'terraform plan' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCS plan"] 
  - id: 'terraform apply' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCS apply  -auto-approve "] 
    
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=big-query init"]
  - id: 'terraform validate'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=big-query validate"]   
  - id: 'terraform plan' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=big-query plan"] 
  - id: 'terraform apply' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=big-query apply  -auto-approve "] 
    
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=data-transfer init"]
  - id: 'terraform validate'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=data-transfer validate"]   
  - id: 'terraform plan' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=data-transfer plan"] 
  - id: 'terraform apply' 
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=data-transfer apply  -auto-approve "] 
 
