steps:
- name:'gcr.io/cloud-builders/gsutil'
  args: 
  - c
  - |
    gcloud builds submit --config=GCS/cloudbuild.yaml
- name:'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - c
  - |
    gcloud builds submit --config=big-query/cloudbuild.yaml 
