steps:
- name:'gcr.io/cloud-builders/gsutil'
  args: 
  - apply
  - -f
  - GCS/cloudbuild.yaml
- name:'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - apply
  - -f
  - big-query/cloudbuild.yaml 
