steps:
- name:'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: ["-c", "terraform GCS/cloudbuild.yaml"]
- name:'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args: ["-c", "terraform big-query/cloudbuild.yaml "]

