steps:
- name:'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    'gcloud builds -f GCS/cloudbuild.yaml'
- name:'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    'gcloud builds -f big-query/cloudbuild.yaml'
