steps:
- name:'gcr.io/cloud-builders/gcloud'
  args: 
  - '-c'
  - |
    gcloud builds submit --config=GCS/cloudbuild.yaml
- name:'gcr.io/cloud-builders/gcloud'
  args:
  - '-c'
  - |
    gcloud builds submit --config=big-query/cloudbuild.yaml
