version: 0.2
env:
  variables:
    build_version: "0.1"
  pre_build:
    commands:
      - curr_working_dir=`GCS`
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve
      
      - curr_working_dir=`big-query`
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve
      
      - curr_working_dir=`data-transfer`
      - terraform init
      - terraform validate
      - terraform plan
      - terraform apply -auto-approve
